# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import Server_pb2 as protos_dot_Server__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/Server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServerStub(object):
    """服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ACallP_sample_align = channel.unary_unary(
                '/Server.Server/ACallP_sample_align',
                request_serializer=protos_dot_Server__pb2.ServerRequest.SerializeToString,
                response_deserializer=protos_dot_Server__pb2.ServerResponse.FromString,
                _registered_method=True)
        self.ComputeHash = channel.unary_unary(
                '/Server.Server/ComputeHash',
                request_serializer=protos_dot_Server__pb2.IndexRequest.SerializeToString,
                response_deserializer=protos_dot_Server__pb2.HashResponse.FromString,
                _registered_method=True)
        self.ASendMessage = channel.unary_unary(
                '/Server.Server/ASendMessage',
                request_serializer=protos_dot_Server__pb2.MessageRequest.SerializeToString,
                response_deserializer=protos_dot_Server__pb2.Empty.FromString,
                _registered_method=True)
        self.PSendMessage = channel.unary_unary(
                '/Server.Server/PSendMessage',
                request_serializer=protos_dot_Server__pb2.MessageRequest.SerializeToString,
                response_deserializer=protos_dot_Server__pb2.Empty.FromString,
                _registered_method=True)
        self.AWaitForMessage = channel.unary_unary(
                '/Server.Server/AWaitForMessage',
                request_serializer=protos_dot_Server__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_Server__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.PWaitForMessage = channel.unary_unary(
                '/Server.Server/PWaitForMessage',
                request_serializer=protos_dot_Server__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_Server__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.BQBoost = channel.unary_unary(
                '/Server.Server/BQBoost',
                request_serializer=protos_dot_Server__pb2.SeriesRequest.SerializeToString,
                response_deserializer=protos_dot_Server__pb2.SeriesResponse.FromString,
                _registered_method=True)
        self.DIBoost = channel.unary_unary(
                '/Server.Server/DIBoost',
                request_serializer=protos_dot_Server__pb2.SeriesRequest.SerializeToString,
                response_deserializer=protos_dot_Server__pb2.DISeriesResponse.FromString,
                _registered_method=True)
        self.LoadEncryptedNumber = channel.unary_unary(
                '/Server.Server/LoadEncryptedNumber',
                request_serializer=protos_dot_Server__pb2.SeriesRequest.SerializeToString,
                response_deserializer=protos_dot_Server__pb2.SeriesRequest.FromString,
                _registered_method=True)
        self.GetPublicKey = channel.unary_unary(
                '/Server.Server/GetPublicKey',
                request_serializer=protos_dot_Server__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_Server__pb2.PublicKey.FromString,
                _registered_method=True)
        self.GetPrivateKey = channel.unary_unary(
                '/Server.Server/GetPrivateKey',
                request_serializer=protos_dot_Server__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_Server__pb2.PrivateKey.FromString,
                _registered_method=True)
        self.GetDecryptedSplits = channel.unary_unary(
                '/Server.Server/GetDecryptedSplits',
                request_serializer=protos_dot_Server__pb2.SplitsRequest.SerializeToString,
                response_deserializer=protos_dot_Server__pb2.SplitsResponse.FromString,
                _registered_method=True)
        self.DecryptGradientHessian = channel.unary_unary(
                '/Server.Server/DecryptGradientHessian',
                request_serializer=protos_dot_Server__pb2.SeriesRequest.SerializeToString,
                response_deserializer=protos_dot_Server__pb2.SeriesResponse.FromString,
                _registered_method=True)
        self.PSendFile = channel.unary_unary(
                '/Server.Server/PSendFile',
                request_serializer=protos_dot_Server__pb2.FileRequest.SerializeToString,
                response_deserializer=protos_dot_Server__pb2.Empty.FromString,
                _registered_method=True)
        self.AGetFile = channel.unary_unary(
                '/Server.Server/AGetFile',
                request_serializer=protos_dot_Server__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_Server__pb2.FileRequest.FromString,
                _registered_method=True)
        self.ASendFile = channel.unary_unary(
                '/Server.Server/ASendFile',
                request_serializer=protos_dot_Server__pb2.FileRequest.SerializeToString,
                response_deserializer=protos_dot_Server__pb2.Empty.FromString,
                _registered_method=True)
        self.PGetFile = channel.unary_unary(
                '/Server.Server/PGetFile',
                request_serializer=protos_dot_Server__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_Server__pb2.FileRequest.FromString,
                _registered_method=True)


class ServerServicer(object):
    """服务定义
    """

    def ACallP_sample_align(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeHash(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ASendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PSendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AWaitForMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PWaitForMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BQBoost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DIBoost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadEncryptedNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPublicKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrivateKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDecryptedSplits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecryptGradientHessian(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PSendFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AGetFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ASendFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PGetFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ACallP_sample_align': grpc.unary_unary_rpc_method_handler(
                    servicer.ACallP_sample_align,
                    request_deserializer=protos_dot_Server__pb2.ServerRequest.FromString,
                    response_serializer=protos_dot_Server__pb2.ServerResponse.SerializeToString,
            ),
            'ComputeHash': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeHash,
                    request_deserializer=protos_dot_Server__pb2.IndexRequest.FromString,
                    response_serializer=protos_dot_Server__pb2.HashResponse.SerializeToString,
            ),
            'ASendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ASendMessage,
                    request_deserializer=protos_dot_Server__pb2.MessageRequest.FromString,
                    response_serializer=protos_dot_Server__pb2.Empty.SerializeToString,
            ),
            'PSendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.PSendMessage,
                    request_deserializer=protos_dot_Server__pb2.MessageRequest.FromString,
                    response_serializer=protos_dot_Server__pb2.Empty.SerializeToString,
            ),
            'AWaitForMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.AWaitForMessage,
                    request_deserializer=protos_dot_Server__pb2.Empty.FromString,
                    response_serializer=protos_dot_Server__pb2.MessageResponse.SerializeToString,
            ),
            'PWaitForMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.PWaitForMessage,
                    request_deserializer=protos_dot_Server__pb2.Empty.FromString,
                    response_serializer=protos_dot_Server__pb2.MessageResponse.SerializeToString,
            ),
            'BQBoost': grpc.unary_unary_rpc_method_handler(
                    servicer.BQBoost,
                    request_deserializer=protos_dot_Server__pb2.SeriesRequest.FromString,
                    response_serializer=protos_dot_Server__pb2.SeriesResponse.SerializeToString,
            ),
            'DIBoost': grpc.unary_unary_rpc_method_handler(
                    servicer.DIBoost,
                    request_deserializer=protos_dot_Server__pb2.SeriesRequest.FromString,
                    response_serializer=protos_dot_Server__pb2.DISeriesResponse.SerializeToString,
            ),
            'LoadEncryptedNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadEncryptedNumber,
                    request_deserializer=protos_dot_Server__pb2.SeriesRequest.FromString,
                    response_serializer=protos_dot_Server__pb2.SeriesRequest.SerializeToString,
            ),
            'GetPublicKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPublicKey,
                    request_deserializer=protos_dot_Server__pb2.Empty.FromString,
                    response_serializer=protos_dot_Server__pb2.PublicKey.SerializeToString,
            ),
            'GetPrivateKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrivateKey,
                    request_deserializer=protos_dot_Server__pb2.Empty.FromString,
                    response_serializer=protos_dot_Server__pb2.PrivateKey.SerializeToString,
            ),
            'GetDecryptedSplits': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDecryptedSplits,
                    request_deserializer=protos_dot_Server__pb2.SplitsRequest.FromString,
                    response_serializer=protos_dot_Server__pb2.SplitsResponse.SerializeToString,
            ),
            'DecryptGradientHessian': grpc.unary_unary_rpc_method_handler(
                    servicer.DecryptGradientHessian,
                    request_deserializer=protos_dot_Server__pb2.SeriesRequest.FromString,
                    response_serializer=protos_dot_Server__pb2.SeriesResponse.SerializeToString,
            ),
            'PSendFile': grpc.unary_unary_rpc_method_handler(
                    servicer.PSendFile,
                    request_deserializer=protos_dot_Server__pb2.FileRequest.FromString,
                    response_serializer=protos_dot_Server__pb2.Empty.SerializeToString,
            ),
            'AGetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.AGetFile,
                    request_deserializer=protos_dot_Server__pb2.Empty.FromString,
                    response_serializer=protos_dot_Server__pb2.FileRequest.SerializeToString,
            ),
            'ASendFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ASendFile,
                    request_deserializer=protos_dot_Server__pb2.FileRequest.FromString,
                    response_serializer=protos_dot_Server__pb2.Empty.SerializeToString,
            ),
            'PGetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.PGetFile,
                    request_deserializer=protos_dot_Server__pb2.Empty.FromString,
                    response_serializer=protos_dot_Server__pb2.FileRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Server.Server', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Server.Server', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Server(object):
    """服务定义
    """

    @staticmethod
    def ACallP_sample_align(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Server.Server/ACallP_sample_align',
            protos_dot_Server__pb2.ServerRequest.SerializeToString,
            protos_dot_Server__pb2.ServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputeHash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Server.Server/ComputeHash',
            protos_dot_Server__pb2.IndexRequest.SerializeToString,
            protos_dot_Server__pb2.HashResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ASendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Server.Server/ASendMessage',
            protos_dot_Server__pb2.MessageRequest.SerializeToString,
            protos_dot_Server__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PSendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Server.Server/PSendMessage',
            protos_dot_Server__pb2.MessageRequest.SerializeToString,
            protos_dot_Server__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AWaitForMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Server.Server/AWaitForMessage',
            protos_dot_Server__pb2.Empty.SerializeToString,
            protos_dot_Server__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PWaitForMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Server.Server/PWaitForMessage',
            protos_dot_Server__pb2.Empty.SerializeToString,
            protos_dot_Server__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BQBoost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Server.Server/BQBoost',
            protos_dot_Server__pb2.SeriesRequest.SerializeToString,
            protos_dot_Server__pb2.SeriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DIBoost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Server.Server/DIBoost',
            protos_dot_Server__pb2.SeriesRequest.SerializeToString,
            protos_dot_Server__pb2.DISeriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadEncryptedNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Server.Server/LoadEncryptedNumber',
            protos_dot_Server__pb2.SeriesRequest.SerializeToString,
            protos_dot_Server__pb2.SeriesRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPublicKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Server.Server/GetPublicKey',
            protos_dot_Server__pb2.Empty.SerializeToString,
            protos_dot_Server__pb2.PublicKey.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrivateKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Server.Server/GetPrivateKey',
            protos_dot_Server__pb2.Empty.SerializeToString,
            protos_dot_Server__pb2.PrivateKey.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDecryptedSplits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Server.Server/GetDecryptedSplits',
            protos_dot_Server__pb2.SplitsRequest.SerializeToString,
            protos_dot_Server__pb2.SplitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecryptGradientHessian(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Server.Server/DecryptGradientHessian',
            protos_dot_Server__pb2.SeriesRequest.SerializeToString,
            protos_dot_Server__pb2.SeriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PSendFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Server.Server/PSendFile',
            protos_dot_Server__pb2.FileRequest.SerializeToString,
            protos_dot_Server__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AGetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Server.Server/AGetFile',
            protos_dot_Server__pb2.Empty.SerializeToString,
            protos_dot_Server__pb2.FileRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ASendFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Server.Server/ASendFile',
            protos_dot_Server__pb2.FileRequest.SerializeToString,
            protos_dot_Server__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PGetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Server.Server/PGetFile',
            protos_dot_Server__pb2.Empty.SerializeToString,
            protos_dot_Server__pb2.FileRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
